sensors/urls.py
from django.conf.urls import url
from sensors.views import upload_csv, charts

urlpatterns = [
    url(r'^$', upload_csv,  name='upload_csv'),
    url(r'^charts/$', charts,  name='charts'),
]

sensors_test/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sensors.urls', namespace="sensors")),
]

sensors/models.py
from __future__ import unicode_literals, division
from django.db import models, IntegrityError, transaction
import sys
import csv
import re
import datetime


class SignalCSV:
    """
    This class represent a row read from a CSV file
    """
    def __init__(self):
        self.signal_id = ""
        self.sensor_id = ""
        self.timestamp = None
        self.date = None
        self.date_acquisition = None
        self.value = None

    def __eq__(self, other):
        return self.signal_id == other.signal_id and self.sensor_id == other.sensor_id \
               and self.timestamp == other.timestamp


class SignalTotal:
    """
    This class represents a signal with the sum of all values for the given day and the number of measures (n)
    """
    def __init__(self):
        self.signal_id = ""
        self.sensor_id = ""
        self.date = None
        self.date_acquisition = None
        self.total = None
        self.n = 1


class SignalManager(models.Manager):
    def process_multiple_csv(self, csvfiles):
        """
        Process the CSV files uploaded by the user. First we simply remove all duplicated data
         and then we obtain the totals by day .
        :param csvfiles: The CSV files to be processed.
        :return: Whether the process ended ok or not.
        """
        try:
            data = []
            for csvfile in csvfiles:
                data = self.remove_duplicated_rows(csvfile, data)

            signals = self.obtain_totals(data)
            self.insert_signals(signals)

            return "success"
        except AttributeError:
            print(sys.exc_info())
            return "error"

    def remove_duplicated_rows(self, csvfile, data):
        """
        Remove the duplicated rows in the CSV file. One row is duplicated when another one exists with the same
        signal, timestamp and sensor ID. When this happens we keep the most recent data
        :param csvfile: The csv file to be processed
        :param data: The data we have already processed
        :return: The new data
        """
        sensor_id, date_acquisition = self.parse_csv_filename(csvfile.name)

        try:
            with transaction.atomic():
                Sensor.objects.create(sensor_id=sensor_id)
        except IntegrityError:
            pass

        content = csv.reader(csvfile)
        for row in content:
            signal_from_csv = SignalCSV()
            signal_from_csv.signal_id = row[0]
            signal_from_csv.sensor_id = sensor_id
            signal_from_csv.date_acquisition = date_acquisition
            signal_from_csv.value = float(row[2])
            signal_from_csv.timestamp = row[1]
            signal_from_csv.date = datetime.datetime.fromtimestamp(int(signal_from_csv.timestamp)).strftime('%Y-%m-%d')

            if not data:
                data.append(signal_from_csv)
            else:
                found = False
                for signal in data:
                    # If the data already exists we keep the most recent value
                    if signal_from_csv == signal and signal_from_csv.date_acquisition >= signal.date_acquisition:
                        signal.value = signal_from_csv.value
                        found = True
                if not found:
                    data.append(signal_from_csv)
        return data

    def obtain_totals(self, signal_measurements):
        signals = []
        for signal in signal_measurements:
            signal_with_totals = SignalTotal()
            signal_with_totals.signal_id = signal.signal_id
            signal_with_totals.sensor_id = signal.sensor_id
            signal_with_totals.date = signal.date
            signal_with_totals.date_acquisition = signal.date_acquisition
            signal_with_totals.total = signal.value

            if not signals:
                signals.append(signal_with_totals)
            else:
                found = False
                for element in signals:
                    # If the date and the signal type already exists, we update the values of the day
                    if element.date == signal_with_totals.date and element.signal_id == signal_with_totals.signal_id:
                        element.total += signal_with_totals.total
                        element.n += 1
                        found = True
                if not found:
                    signals.append(signal_with_totals)

        signals = self.calculate_temperature_avg(signals)
        return signals

    @staticmethod
    def parse_csv_filename(csv_filename):
        """
        Parse the name of the CSV file un order to get the signal id (temperature, rainfall, etc.) and
        the acquisition date of the data.
        :param csv_filename: The name of the CSV file
        :return: signal_id, date_acquisition

        """
        # Regexp for <sensor_id>-<ddmmyyyy>.csv
        filename_regexp = re.search('(.*)-(\d{2}\d{2}\d{4})\.csv', csv_filename)

        if filename_regexp:
            signal_id = filename_regexp.group(1)
            date_acquisition = filename_regexp.group(2)
            date_acquisition = datetime.datetime.strptime(date_acquisition, '%d%m%Y')

            return signal_id, date_acquisition

        raise AttributeError

    @staticmethod
    def calculate_temperature_avg(signals):
        for signal in signals:
            if signal.signal_id == "temperature":
                signal.total /= float(signal.n)
        return signals

    @staticmethod
    def insert_signals(signals):
        for signal in signals:
            Signal.objects.create(
                sensor_id=signal.sensor_id,
                signal_id=signal.signal_id,
                date=signal.date,
                date_acquisition=signal.date_acquisition,
                value=signal.total
            )


class Signal(models.Model):
    sensor_id = models.CharField(max_length=20)
    signal_id = models.CharField(max_length=20)
    date = models.DateField()
    date_acquisition = models.DateField()
    value = models.FloatField()

    objects = SignalManager()

    class Meta:
        db_table = "signal"


class Sensor(models.Model):
    sensor_id = models.CharField(max_length=20, primary_key=True)

    class Meta:
        db_table = "sensor"


class SignalType(models.Model):
    signal_type = models.CharField(max_length=20, primary_key=True)

    class Meta:
        db_table = "signal_type"

sensors/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.db import transaction
import json

from sensors.models import Signal, SignalType, Sensor
import reports


@transaction.atomic
def upload_csv(request):
    if request.method == 'POST':
        data = {}
        Signal.objects.process_csv(request.FILES.getlist("filebutton"))
        data["success"] = "success"
        return HttpResponse(json.dumps(data), content_type='application/json')

    return render(request, 'upload_csv.html')


def charts(request):
    sensor_id = request.GET.get('sensor', None)
    signal_id = request.GET.get('signal', None)
    if sensor_id:
        data = {}
        signals = Signal.objects.filter(sensor_id=sensor_id, signal_id=signal_id).order_by('date')
        data['chart_data'] = reports.ChartData.convert_data_to_json(signals)

        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        request = __init_session(request)
        return render(request, 'chart_test.html')


def __init_session(request):
    if "signal_types" not in request.session:
        signal_types = SignalType.objects.values_list('signal_type', flat=True).all()
        if signal_types:
            request.session["signal_types"] = list(signal_types)

    if "sensors" not in request.session:
        sensors = Sensor.objects.values_list('sensor_id', flat=True).all()
        if sensors:
            request.session["sensors"] = list(sensors)

    return request

sensors/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>{% block title %}My Sensor App{% endblock %}</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Custom styles for this template -->
        {% load static %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              <a class="navbar-brand" href="#">Sensors Data</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'sensors:upload_csv' %}">Upload CSV</a></li>
                    <li><a href="{% url 'sensors:charts' %}">Charts</a></li>
                </ul>
            </div><!--/.nav-collapse -->
            </div>
        </nav>

       {% block container %}{% endblock %}

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <script src="http://code.highcharts.com/highcharts.js"></script>

        {% block customjs %}{% endblock %}
    </body>
</html>

sensors/templates/chart_test.html
{% extends 'base.html' %}

{% block title %}Charts{% endblock %}

{% block container %}
<div class="container">
    <form id="form-chart" class="form-horizontal starter-template" action="{% url 'sensors:charts' %}" method="get">
    {% csrf_token %}
    <fieldset>

    <!-- Form Name -->
    <legend>Create your Chart</legend>

    <!-- Select Basic -->
    <div class="form-group">
        <label class="col-md-4 control-label" for="selectbasic">Sensor ID</label>
        <div class="col-md-4">
            <select id="sensor" name="sensor" class="form-control">
                {% for value in request.session.sensors %}
                    <option value="{{ value }}">{{ value }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
        <label class="col-md-4 control-label" for="selectbasic">Signal</label>
        <div class="col-md-4">
            <select id="signal" name="signal" class="form-control">
                {% for value in request.session.signal_types %}
                    <option value="{{ value }}">{{ value }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <!-- Button -->
    <div class="form-group">
        <label class="col-md-4 control-label" for="singlebutton"></label>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary">View Chart</button>
        </div>
    </div>

    </fieldset>
    </form>
</div>

<div class="panel panel-default">
    <div id="chart_panel" class="panel-body" style="width:100%;height:314px"></div>
</div>
{% endblock %}

{% block customjs %}
    {% load static %}
    <!-- Custom scripts -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

sensors/templates/charts.html
{% extends 'base.html' %}

{% block title %}Charts{% endblock %}

{% block container %}
<div id="container" style="width:100%; height:400px;"></div>
{% endblock %}

{% block chart %}
<script>
    $(function () {
        $('#container').highcharts({
            chart: {
                zoomType: 'xy'
            },
            title: {
                text: 'Average Monthly Temperature and Rainfall in Tokyo'
            },
            subtitle: {
                text: 'Source: WorldClimate.com'
            },
            xAxis: [{
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                crosshair: true
            }],
            yAxis: [{ // Primary yAxis
                labels: {
                    format: '{value}°C',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                title: {
                    text: 'Temperature',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                }
            }, { // Secondary yAxis
                title: {
                    text: 'Rainfall',
                    style: {
                        color: Highcharts.getOptions().colors[0]
                    }
                },
                labels: {
                    format: '{value} mm',
                    style: {
                        color: Highcharts.getOptions().colors[0]
                    }
                },
                opposite: true
            }],
            tooltip: {
                shared: true
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                x: 120,
                verticalAlign: 'top',
                y: 100,
                floating: true,
                backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
            },
            series: [{
                name: 'Rainfall',
                type: 'column',
                yAxis: 1,
                data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
                tooltip: {
                    valueSuffix: ' mm'
                }

            }, {
                name: 'Temperature',
                type: 'spline',
                data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
                tooltip: {
                    valueSuffix: '°C'
                }
            }]
        });
    });
</script>
{% endblock %}

sensors/templates/upload_csv.html
{% extends 'base.html' %}

{% block title %}My Sensor app{% endblock %}

{% block container %}
    <div class="container">
        <form id="form-csv" class="starter-template" action="{% url 'sensors:upload_csv' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>

            <!-- Form Name -->
            <legend>Upload your CSV file</legend>

            <!-- File Button -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="filebutton">CSV FIle</label>
                <div class="col-md-4">
                <input id="filebutton" name="filebutton" class="input-file" type="file" accept=".csv" multiple/>
                </div>
            </div>

            </fieldset>
            <button type="submit" id="submit-csv" class="btn btn-primary">Upload</button>
        </form>
        <div id="feedback" class="alert-dismissible"></div>
    </div><!-- /.container -->
{% endblock %}

{% block customjs %}
    {% load static %}
    <!-- Custom scripts -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}